### ISSUE TITLE
sprite sheet heuristic for trees

### ISSUE THREAD

**Issue by roysmeding** [roysmeding/sv_render#6]
currently we decide the sprite sheet used for a tree based on the 'treeType' field in the save, but this isn't correct because there are missing spritesheets for some of these treeType values.

someone needs to verify which treeType, growthStage, etc. is rendered in what way in-game.

**Comment by Skyyrunner** [comment]
the tree numbers without a spritesheet are probably young trees :v

**Comment by roysmeding** [comment]
I don't think so. Young trees have unique sprites depending on type (maple, oak etc.) too, AFAIK. But someone should verify it. :p

**Comment by Skyyrunner** [comment]
![](http://i.imgur.com/vBDMbve.png)

screenshot of the current state.

The tilesheet.json for the trees has to be: 

    {
    	"src":     "TerrainFeatures/tree#_spring",
    	"img_src": "TerrainFeatures/tree#_spring.png",
    	"sheet_size": [ 3, 10 ],
	    "tile_size":  [ 16, 16 ]
    }

where # is the appropriate number.
